export const TOP_IDEAS = [
  {
    id: 1,
    name: 'AI-Powered Productivity',
    category: 'Technology',
    revivalProbability: 92,
    trendScore: 9.5,
    states: ['Birth', 'Growth', 'Peak', 'Decline', 'Dormancy', 'Revival'],
    progressionValues: [15, 45, 95, 70, 35, 85],
    description: 'The integration of artificial intelligence into daily work workflows to automate repetitive tasks, enhance decision-making, and amplify human creative capacity.',
    meaning: 'AI-Powered Productivity refers to leveraging machine learning, generative AI, and automation tools to fundamentally transform how humans accomplish knowledge work.',
    trend: 'rising',
    origin_year: 2017,
    historical_context: 'Emerged from early automation tools, accelerated dramatically with the release of ChatGPT in late 2022. The concept went mainstream as companies raced to integrate LLMs into productivity suites.',
    key_events: [
      { year: 2017, event: 'Google introduces AI-first strategy; early automation tools proliferate' },
      { year: 2020, event: 'COVID-19 forces remote work, accelerating adoption of digital productivity tools' },
      { year: 2022, event: 'ChatGPT launches, bringing generative AI to the mass market' },
      { year: 2023, event: 'Microsoft Copilot, Google Bard, and 1000+ AI productivity startups emerge' },
      { year: 2024, event: 'Enterprise AI adoption reaches 78%; AI replaces 15% of entry-level knowledge work' },
    ],
    year_data: [
      { year: 2017, state: 'Birth', score: 15 },
      { year: 2018, state: 'Birth', score: 22 },
      { year: 2019, state: 'Growth', score: 35 },
      { year: 2020, state: 'Growth', score: 52 },
      { year: 2021, state: 'Growth', score: 68 },
      { year: 2022, state: 'Peak', score: 82 },
      { year: 2023, state: 'Peak', score: 95 },
      { year: 2024, state: 'Peak', score: 92 },
      { year: 2025, state: 'Peak', score: 89 },
    ],
  },
  {
    id: 2,
    name: 'Stoicism & Mental Health',
    category: 'Philosophy',
    revivalProbability: 78,
    trendScore: 8.7,
    states: ['Birth', 'Growth', 'Peak', 'Decline', 'Dormancy', 'Revival'],
    progressionValues: [20, 50, 85, 65, 40, 72],
    description: 'The modern revival of ancient Stoic philosophy as a framework for emotional resilience, anxiety management, and mental wellness in a hyperconnected world.',
    meaning: 'Stoicism teaches that external events are outside our control, but our responses are within it — applied today as a toolkit for reducing anxiety and building mental fortitude.',
    trend: 'rising',
    origin_year: 2012,
    historical_context: 'Ryan Holiday\'s "The Obstacle Is the Way" (2014) sparked a modern renaissance of Stoic philosophy, merging ancient wisdom with startup culture and self-help movements.',
    key_events: [
      { year: 2012, event: 'Tim Ferriss begins popularizing Stoicism on his podcast' },
      { year: 2014, event: 'Ryan Holiday publishes "The Obstacle Is the Way" — bestseller' },
      { year: 2018, event: 'Global mental health crisis drives search for practical philosophy' },
      { year: 2020, event: 'Pandemic makes Stoic resilience frameworks go viral on social media' },
      { year: 2023, event: 'Academic institutions begin formal Stoicism wellness programs' },
    ],
    year_data: [
      { year: 2012, state: 'Birth', score: 20 },
      { year: 2014, state: 'Growth', score: 38 },
      { year: 2016, state: 'Growth', score: 52 },
      { year: 2018, state: 'Growth', score: 65 },
      { year: 2020, state: 'Peak', score: 80 },
      { year: 2022, state: 'Peak', score: 85 },
      { year: 2024, state: 'Peak', score: 78 },
      { year: 2025, state: 'Revival', score: 72 },
    ],
  },
  {
    id: 3,
    name: 'Decentralized Finance',
    category: 'Technology',
    revivalProbability: 65,
    trendScore: 7.2,
    states: ['Birth', 'Growth', 'Peak', 'Decline', 'Dormancy', 'Revival'],
    progressionValues: [25, 70, 90, 50, 25, 55],
    description: 'A blockchain-based financial ecosystem that removes traditional intermediaries like banks, enabling peer-to-peer lending, trading, and financial services globally.',
    meaning: 'DeFi (Decentralized Finance) uses smart contracts on blockchains to recreate financial instruments without relying on central authorities, making finance permissionless and open.',
    trend: 'stable',
    origin_year: 2018,
    historical_context: 'Born from Ethereum\'s smart contract capabilities, DeFi exploded during 2020-2021\'s "DeFi Summer" before collapsing with the crypto bear market of 2022.',
    key_events: [
      { year: 2018, event: 'MakerDAO launches first major DeFi protocol on Ethereum' },
      { year: 2020, event: '"DeFi Summer" — total value locked reaches $13 billion' },
      { year: 2021, event: 'DeFi peaks at $250B TVL; yield farming becomes mainstream' },
      { year: 2022, event: 'Terra/LUNA collapse wipes $40B; crypto winter begins' },
      { year: 2023, event: 'Regulatory scrutiny intensifies; industry rebuilds with compliance focus' },
    ],
    year_data: [
      { year: 2018, state: 'Birth', score: 25 },
      { year: 2019, state: 'Growth', score: 45 },
      { year: 2020, state: 'Growth', score: 70 },
      { year: 2021, state: 'Peak', score: 90 },
      { year: 2022, state: 'Decline', score: 50 },
      { year: 2023, state: 'Dormancy', score: 25 },
      { year: 2024, state: 'Revival', score: 42 },
      { year: 2025, state: 'Revival', score: 55 },
    ],
  },
  {
    id: 4,
    name: 'Minimalism Lifestyle',
    category: 'Culture',
    revivalProbability: 71,
    trendScore: 7.9,
    states: ['Birth', 'Growth', 'Peak', 'Decline', 'Dormancy', 'Revival'],
    progressionValues: [30, 60, 80, 55, 35, 68],
    description: 'A counter-cultural movement rejecting excess consumerism in favour of intentional living — owning fewer possessions, simplifying spaces, and prioritizing experiences over things.',
    meaning: 'Minimalism is the philosophy that less is more — eliminating the non-essential to make room for what truly matters: relationships, purpose, and quality of life.',
    trend: 'stable',
    origin_year: 2010,
    historical_context: 'Marie Kondo\'s KonMari method and "The Minimalists" documentary brought the concept mainstream, merging Japanese wabi-sabi aesthetics with Western anti-consumerism.',
    key_events: [
      { year: 2010, event: '"The Minimalists" blog launches; concept spreads online' },
      { year: 2014, event: 'Marie Kondo publishes "The Life-Changing Magic of Tidying Up"' },
      { year: 2019, event: 'Netflix series "Tidying Up with Marie Kondo" hits #1 globally' },
      { year: 2021, event: 'Pandemic drives "decluttering" trend; minimalist home design peaks' },
      { year: 2023, event: '"Underconsumption core" trend emerges on TikTok as next evolution' },
    ],
    year_data: [
      { year: 2010, state: 'Birth', score: 30 },
      { year: 2013, state: 'Growth', score: 48 },
      { year: 2016, state: 'Growth', score: 60 },
      { year: 2019, state: 'Peak', score: 80 },
      { year: 2021, state: 'Peak', score: 75 },
      { year: 2023, state: 'Decline', score: 55 },
      { year: 2025, state: 'Revival', score: 68 },
    ],
  },
  {
    id: 5,
    name: 'Remote Work Culture',
    category: 'Work',
    revivalProbability: 88,
    trendScore: 9.1,
    states: ['Birth', 'Growth', 'Peak', 'Decline', 'Dormancy', 'Revival'],
    progressionValues: [10, 40, 95, 85, 70, 92],
    description: 'The organizational shift away from centralized office environments toward distributed, flexible work arrangements enabled by digital collaboration tools.',
    meaning: 'Remote Work Culture encompasses the norms, tools, and practices that allow knowledge workers to perform their jobs effectively from any location — home, cafe, or co-working spaces globally.',
    trend: 'rising',
    origin_year: 2015,
    historical_context: 'While remote work existed before COVID-19, the 2020 pandemic forced a global experiment that permanently reshaped workplace expectations for hundreds of millions of workers.',
    key_events: [
      { year: 2015, event: 'Slack launches; Zoom grows; "digital nomad" lifestyle gains traction' },
      { year: 2019, event: 'Remote work adoption at 5% globally in knowledge work sector' },
      { year: 2020, event: 'COVID-19: global forced remote work experiment begins simultaneously' },
      { year: 2021, event: '"Great Resignation" — workers demand remote flexibility as standard' },
      { year: 2023, event: 'Return-to-office mandates spark backlash; hybrid becomes new standard' },
      { year: 2025, event: 'AI tools enable async-first global teams; "talent is everywhere" era' },
    ],
    year_data: [
      { year: 2015, state: 'Birth', score: 10 },
      { year: 2017, state: 'Growth', score: 28 },
      { year: 2019, state: 'Growth', score: 40 },
      { year: 2020, state: 'Peak', score: 95 },
      { year: 2021, state: 'Peak', score: 92 },
      { year: 2022, state: 'Decline', score: 85 },
      { year: 2023, state: 'Decline', score: 78 },
      { year: 2024, state: 'Revival', score: 88 },
    ],
  },
  {
    id: 6,
    name: 'Climate Consciousness',
    category: 'Environment',
    revivalProbability: 82,
    trendScore: 8.4,
    states: ['Birth', 'Growth', 'Peak', 'Decline', 'Dormancy', 'Revival'],
    progressionValues: [20, 55, 85, 75, 55, 79],
    description: 'A cultural shift in individual and collective awareness about climate change, driving behavioural changes in consumption, energy use, diet, and political engagement.',
    meaning: 'Climate Consciousness means understanding one\'s environmental impact and actively choosing lifestyles, businesses, and policies that reduce carbon footprint and protect ecosystems.',
    trend: 'rising',
    origin_year: 2006,
    historical_context: 'Al Gore\'s "An Inconvenient Truth" (2006) planted seeds, but Greta Thunberg\'s 2018 school strikes and the global climate march ignited a generational consciousness shift.',
    key_events: [
      { year: 2006, event: '"An Inconvenient Truth" brings climate crisis to mainstream awareness' },
      { year: 2015, event: 'Paris Agreement signed by 196 nations; climate becomes policy priority' },
      { year: 2018, event: 'Greta Thunberg begins Fridays for Future; school strike movement goes global' },
      { year: 2021, event: 'IPCC "Code Red" report; COP26 marks turning point in corporate pledges' },
      { year: 2023, event: 'Record temperatures globally; climate anxiety becomes documented condition' },
    ],
    year_data: [
      { year: 2006, state: 'Birth', score: 20 },
      { year: 2010, state: 'Growth', score: 38 },
      { year: 2015, state: 'Growth', score: 55 },
      { year: 2018, state: 'Peak', score: 78 },
      { year: 2021, state: 'Peak', score: 85 },
      { year: 2023, state: 'Decline', score: 75 },
      { year: 2025, state: 'Revival', score: 79 },
    ],
  },
  {
    id: 7,
    name: 'Biohacking & Longevity',
    category: 'Health',
    revivalProbability: 75,
    trendScore: 8.2,
    states: ['Birth', 'Growth', 'Peak', 'Decline', 'Dormancy', 'Revival'],
    progressionValues: [18, 52, 78, 62, 40, 70],
    description: 'A movement of individuals using science, technology, and self-experimentation to optimize biological performance, slow aging, and extend healthspan.',
    meaning: 'Biohacking treats the human body as a system that can be upgraded — through fasting, supplements, wearables, genetic testing, and cutting-edge longevity interventions.',
    trend: 'rising',
    origin_year: 2011,
    historical_context: 'Dave Asprey coined "Biohacking" around 2011 with Bulletproof Coffee. The concept exploded post-2020 as tech billionaires like Bryan Johnson publicly pursued radical life extension.',
    key_events: [
      { year: 2011, event: 'Dave Asprey launches Bulletproof; popularizes term "biohacking"' },
      { year: 2016, event: 'Oura Ring, WHOOP wearables emerge; continuous monitoring goes consumer' },
      { year: 2020, event: 'Pandemic drives interest in immune optimization and longevity science' },
      { year: 2023, event: 'Bryan Johnson\'s "Project Blueprint" goes viral; longevity industry hits $44B' },
      { year: 2024, event: 'GLP-1 drugs (Ozempic) merge with longevity narrative; mainstream adoption' },
    ],
    year_data: [
      { year: 2011, state: 'Birth', score: 18 },
      { year: 2014, state: 'Growth', score: 35 },
      { year: 2017, state: 'Growth', score: 52 },
      { year: 2020, state: 'Growth', score: 65 },
      { year: 2022, state: 'Peak', score: 78 },
      { year: 2023, state: 'Peak', score: 75 },
      { year: 2025, state: 'Revival', score: 70 },
    ],
  },
  {
    id: 8,
    name: 'Digital Minimalism',
    category: 'Technology',
    revivalProbability: 69,
    trendScore: 7.5,
    states: ['Birth', 'Growth', 'Peak', 'Decline', 'Dormancy', 'Revival'],
    progressionValues: [22, 48, 72, 58, 38, 65],
    description: 'A philosophy of intentional technology use — choosing which digital tools to engage with, and how, to maximize wellbeing and minimize distraction and anxiety.',
    meaning: 'Digital Minimalism, coined by Cal Newport, advocates for using technology deliberately and selectively, rather than reflexively — treating attention as a finite resource to protect.',
    trend: 'stable',
    origin_year: 2016,
    historical_context: 'As smartphone addiction became documented and social media\'s mental health impact was exposed by Facebook whistleblowers, a counter-movement of intentional tech use emerged.',
    key_events: [
      { year: 2016, event: 'First "digital detox" retreats emerge; screen time awareness grows' },
      { year: 2019, event: 'Cal Newport publishes "Digital Minimalism" — NYT bestseller' },
      { year: 2021, event: 'Frances Haugen testifies: Facebook knowingly harms mental health' },
      { year: 2022, event: 'Screen Time features on iOS/Android normalize usage monitoring' },
      { year: 2024, event: 'EU Digital Services Act forces transparency; Gen Z leads "offline" movement' },
    ],
    year_data: [
      { year: 2016, state: 'Birth', score: 22 },
      { year: 2018, state: 'Growth', score: 42 },
      { year: 2020, state: 'Growth', score: 58 },
      { year: 2021, state: 'Peak', score: 72 },
      { year: 2023, state: 'Decline', score: 58 },
      { year: 2025, state: 'Revival', score: 65 },
    ],
  },
  {
    id: 9,
    name: 'Metaverse & Web3',
    category: 'Technology',
    revivalProbability: 58,
    trendScore: 6.8,
    states: ['Birth', 'Growth', 'Peak', 'Decline', 'Dormancy', 'Revival'],
    progressionValues: [35, 65, 75, 40, 20, 45],
    description: 'The vision of a persistent, shared virtual universe combining augmented reality, virtual reality, blockchain ownership, and social interaction into a new layer of reality.',
    meaning: 'The Metaverse envisions an immersive internet where people work, play, and socialize in 3D virtual worlds — with Web3 providing the economic layer via NFTs and crypto.',
    trend: 'declining',
    origin_year: 2021,
    historical_context: 'Mark Zuckerberg\'s Meta rebrand in October 2021 set off a frenzy, but poor execution, clunky hardware, and the crypto crash deflated the hype rapidly by 2023.',
    key_events: [
      { year: 2021, event: 'Facebook rebrands to Meta; Metaverse becomes $1T investment narrative' },
      { year: 2022, event: 'NFT market collapses 97%; Metaverse adoption stalls at <1% of internet users' },
      { year: 2023, event: 'Apple Vision Pro launches — spatial computing reframes the narrative' },
      { year: 2024, event: 'Meta\'s Horizon Worlds reaches 500K MAU — far below projections' },
      { year: 2025, event: 'AI agents in virtual spaces offer new revival pathway for the concept' },
    ],
    year_data: [
      { year: 2021, state: 'Birth', score: 35 },
      { year: 2022, state: 'Peak', score: 75 },
      { year: 2023, state: 'Decline', score: 40 },
      { year: 2024, state: 'Dormancy', score: 20 },
      { year: 2025, state: 'Revival', score: 45 },
    ],
  },
  {
    id: 10,
    name: 'TikTok Culture',
    category: 'Social Media',
    revivalProbability: 64,
    trendScore: 7.1,
    states: ['Birth', 'Growth', 'Peak', 'Decline', 'Dormancy', 'Revival'],
    progressionValues: [40, 85, 92, 68, 45, 62],
    description: 'The cultural ecosystem born from short-form video — characterized by viral trends, creator economy, micro-niches, algorithm-driven discovery, and Gen Z identity formation.',
    meaning: 'TikTok Culture represents a new media paradigm where anyone can achieve virality, trends cycle in days not years, and culture is created bottom-up rather than top-down.',
    trend: 'stable',
    origin_year: 2018,
    historical_context: 'ByteDance\'s TikTok merged with Musical.ly in 2018 and grew to 1 billion users by 2021. It fundamentally changed how music, fashion, food, and ideas spread globally.',
    key_events: [
      { year: 2018, event: 'TikTok merges with Musical.ly; launches internationally' },
      { year: 2020, event: 'Pandemic lockdowns make TikTok the #1 downloaded app globally' },
      { year: 2021, event: '1 billion active users; "TikTok brain" and attention span debates begin' },
      { year: 2023, event: 'US Congressional hearings on TikTok; ban threat drives uncertainty' },
      { year: 2025, event: 'Short-form video format now standard across all platforms (Reels, Shorts)' },
    ],
    year_data: [
      { year: 2018, state: 'Birth', score: 40 },
      { year: 2019, state: 'Growth', score: 65 },
      { year: 2020, state: 'Growth', score: 85 },
      { year: 2021, state: 'Peak', score: 92 },
      { year: 2022, state: 'Peak', score: 88 },
      { year: 2023, state: 'Decline', score: 68 },
      { year: 2024, state: 'Decline', score: 55 },
      { year: 2025, state: 'Revival', score: 62 },
    ],
  },
];

export const SCENARIO_PRESETS = {
  optimistic: {
    economicConditions: 80,
    mentalHealthIndex: 75,
    socialTrendIntensity: 85,
    productivityCulture: 90,
    socialFragmentation: 20,
    region: 'Global',
  },
  pessimistic: {
    economicConditions: 30,
    mentalHealthIndex: 35,
    socialTrendIntensity: 25,
    productivityCulture: 40,
    socialFragmentation: 80,
    region: 'Global',
  },
  neutral: {
    economicConditions: 50,
    mentalHealthIndex: 50,
    socialTrendIntensity: 50,
    productivityCulture: 50,
    socialFragmentation: 50,
    region: 'Global',
  },
};

// Region-based scenario auto-presets (derived from real cultural indices)
export const REGION_PRESETS = {
  'Global': {
    economicConditions: 50, mentalHealthIndex: 50,
    socialTrendIntensity: 55, productivityCulture: 55, socialFragmentation: 50,
    description: 'Averaged global conditions across all major markets.',
  },
  'North America': {
    economicConditions: 62, mentalHealthIndex: 40,
    socialTrendIntensity: 80, productivityCulture: 85, socialFragmentation: 70,
    description: 'High productivity culture, mental health crisis, strong social media influence.',
  },
  'Europe': {
    economicConditions: 55, mentalHealthIndex: 58,
    socialTrendIntensity: 60, productivityCulture: 55, socialFragmentation: 45,
    description: 'Work-life balance prioritized, moderate economic conditions, lower fragmentation.',
  },
  'Asia-Pacific': {
    economicConditions: 68, mentalHealthIndex: 45,
    socialTrendIntensity: 85, productivityCulture: 90, socialFragmentation: 38,
    description: 'Very high productivity culture, fast-moving trends, strong community cohesion.',
  },
  'Latin America': {
    economicConditions: 38, mentalHealthIndex: 55,
    socialTrendIntensity: 70, productivityCulture: 50, socialFragmentation: 62,
    description: 'Economic instability, vibrant social culture, moderate fragmentation.',
  },
  'Africa': {
    economicConditions: 32, mentalHealthIndex: 60,
    socialTrendIntensity: 65, productivityCulture: 45, socialFragmentation: 55,
    description: 'Emerging digital economy, strong community ties, high growth trajectory.',
  },
  'Middle East': {
    economicConditions: 65, mentalHealthIndex: 48,
    socialTrendIntensity: 60, productivityCulture: 70, socialFragmentation: 58,
    description: 'Oil-driven economies, rapidly modernizing, cultural conservatism meets tech adoption.',
  },
  'South Asia': {
    economicConditions: 45, mentalHealthIndex: 42,
    socialTrendIntensity: 75, productivityCulture: 80, socialFragmentation: 52,
    description: 'High growth, extreme productivity pressure, massive youth-driven cultural shifts.',
  },
};
